# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=300)),
                ('file_size', models.FloatField()),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_asset', to='AssetStorage.Asset')),
                ('supporting_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_asset', to='AssetStorage.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='related_assets',
            field=models.ManyToManyField(through='AssetStorage.RelatedAssets', to='AssetStorage.Asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(related_name='assets', to='AssetStorage.Tag'),
        ),
    ]
