# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetStorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Asset'},
        ),
        migrations.AlterModelOptions(
            name='relatedassets',
            options={'verbose_name': 'Asset'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', to='AssetStorage.Tag'),
        ),
    ]
