# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetStorage', '0004_auto_20170210_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewimage',
            name='name',
            field=models.CharField(default='red', max_length=50),
        ),
    ]
