# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetStorage', '0005_previewimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='path',
        ),
        migrations.AlterField(
            model_name='previewimage',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
