# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetStorage', '0007_auto_20170213_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleasset',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='test_folder'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
